spring:
  application:
    name: countries
  datasource:
    url: jdbc:postgresql://localhost:5432/sdg
    username: admin
    password: Admin2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    server:
      description: Development server
      url: http://localhost:8080

restcountries:
  base-url: https://restcountries.com
  fields: name,population